# checkpoint-rbac.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: checkpoint-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "get", "watch", "create"]
  - apiGroups: [""]
    resources: ["nodes/checkpoint"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: checkpoint-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: checkpoint-role
subjects:
  - kind: User
    name: system:node:codingbeast
    apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-router-checkpoint-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: checkpoint-role
subjects:
  - kind: ServiceAccount
    name: kube-router
    namespace: kube-system
