---
apiVersion: v1
kind: Service
metadata:
  name: http-server
spec:
  selector:
    app: http-server
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345
      nodePort: 30001 # Set a specific NodePort value
  type: NodePort
