apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-client
  labels:
    app: http-client
  annotations:
    bmv2-cni/role: "client"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-client
  template:
    metadata:
      labels:
        app: http-client
    spec:
      containers:
        - name: http-client
          image: docker.io/skosorin/http-client
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            # P4 load balancer IP
            - name: SERVER_IP
              value: "10.244.1.244"
            - name: SERVER_PORT
              value: "12345"
