apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-client
  labels:
    app: http-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-client
  template:
    metadata:
      labels:
        app: http-client
    spec:
      containers:
        - name: http-client
          image: docker.io/skosorin/http-client
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.5"
            limits:
              memory: "256Mi"
              cpu: "1"
          env:
            # P4 load balancer IP
            - name: SERVER_IP
              value: "10.0.1.10"
            - name: SERVER_PORT
              value: "12345"
