apiVersion: v1
kind: ConfigMap
metadata:
  name: bmv2-cni-config
  namespace: kube-system
data:
  10-bmv2-cni.conf: |
    {
      "cniVersion": "0.3.1",
      "name": "bmv2-cni",
      "type": "bmv2-cni",
      "thriftPort": "9090",
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bmv2-cni-daemonset
  namespace: kube-system
  labels:
    k8s-app: bmv2-cni
spec:
  selector:
    matchLabels:
      name: bmv2-cni
  template:
    metadata:
      labels:
        name: bmv2-cni
    spec:
      hostNetwork: true
      tolerations:
        - key: "node-role.kubernetes.io/master"
          effect: "NoSchedule"
      containers:
        - name: bmv2-switch
          image: docker.io/skosorin/bmv2
          imagePullPolicy: IfNotPresent
          args:
            - "--device-id"
            - "0"
            - "/load_balance.json"
            - "--log-console"
            - "--thrift-port"
            - "9090"
            - "--"
            - "--grpc-server-addr"
            - "0.0.0.0:50051"
          securityContext:
            privileged: true
          volumeMounts:
            - name: load-balance-json
              mountPath: /load_balance.json
              subPath: load_balance.json
            - name: pcap-dir
              mountPath: /pcaps
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        - name: bmv2-controller
          image: docker.io/skosorin/bmv2-controller
          imagePullPolicy: IfNotPresent
          args:
            - "--config"
            - "/config/switches.json"
          volumeMounts:
            - name: config-volume
              mountPath: /config
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          securityContext:
            privileged: true
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt/cni/bin
        - name: cni-conf
          hostPath:
            path: /etc/cni/net.d
        - name: plugin-bin
          hostPath:
            path: /opt/cni/bin
        - name: plugin-conf
          configMap:
            name: bmv2-cni-config
        - name: load-balance-json
          hostPath:
            path: /etc/load_balancer/
        - name: pcap-dir
          emptyDir: {}
        - name: config-volume
          hostPath:
            path: /home/stanley/gsoc/p4containerflow/examples/container_migration_in_kubernetes/config
